# permissions for end users to edit assets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asset-editor-role
rules:
- apiGroups:
  - seals.kinko.dev
  resources:
  - assets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seals.kinko.dev
  resources:
  - assets/status
  verbs:
  - get
