# permissions for end users to view assets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asset-viewer-role
rules:
- apiGroups:
  - seals.kinko.dev
  resources:
  - assets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seals.kinko.dev
  resources:
  - assets/status
  verbs:
  - get
