
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - secrets.kms-secrets-operator
  resources:
  - encryptedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.kms-secrets-operator
  resources:
  - encryptedsecrets/status
  verbs:
  - get
  - patch
  - update
